### ISSUE TITLE
User Story: User - View Services Offered by Barbers

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/Barnets-Barbershop#3]
As a user, I want to see the list of services offered by the barbershop , so that I can, choose the service that are right for me. .

Acceptance criteria:

The app should display a list of services along with their descriptions.
User should be able to see which services are offered by each barber.

## Tasks
- [x] Create service list .
- [ ] Populate service list.
- [ ] Ensure services are displayed accurately.
