### ISSUE TITLE
User Story: User - Create, cancel and update bookings 

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/Barnets-Barbershop#5]
As a user, I want to **create, reschedule and cancel appointments**, so that I can **effectively manage my schedule.**

Acceptance criteria:

User should be able to create cancel and  / or  reschedule and existing appointment.
Cancelled  appointment slot should become available for booking again.
User should receive confirmation upon successful cancellation or update.

## Tasks 

- [x] Develop booking interface
- [x] Create  data models
- [x] Develop create, cancel and edit functionality for appointments.
- [x] Update database upon successful cancellation or update.
- [ ] Ensure cancelled slots become available for booking.
- [ ] Send User email confirmation of new booking made and / or cancellation or update to prior bookings..
