### ISSUE TITLE
User Story: Authentication

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/Barnets-Barbershop#9]
As a user, I want to create an account so that I can book appointments and manage my bookings
Acceptance criteria:

User should be able to provide basic information (name, email, phone number).
User should receive a verification email for account confirmation.
User should be able to log in with the created credentials.
User should be able to re-set account info if log in details are forgotten.

## Tasks
- [x] Implement user registration form.
- [x]  Develop email verification functionality.
- [x] Create login page and authentication process.
- [x] Redirect the user to booking form after registration and  / or log in
